; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+5 on Sun Feb 12 2023 16:23:27 GMT+0300 (Moscow Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


